package com.uu.common.base;

import com.uu.model.baseModel.BaseBastourist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bastourist extends BaseBastourist<Bastourist> {
	
}
